#!/bin/bash
# Simple diagnostics for Hyprland setup
echo "=== HYPRLAND CHECK ==="
command -v Hyprland >/dev/null && echo "Hyprland installed" || echo "Hyprland missing"
echo ""
echo "=== WAYBAR ==="
command -v waybar >/dev/null && echo "waybar installed" || echo "waybar missing"
pgrep waybar >/dev/null && echo "waybar running" || echo "waybar not running"
echo ""
echo "=== FONTS ==="
fc-list | grep -i "nerd\|awesome" | head -5 || echo "Nerd fonts not found"
echo ""
echo "=== AUDIO (pipewire) ==="
systemctl --user is-active pipewire && echo "pipewire active" || echo "pipewire not active"
echo ""
echo "=== BLUETOOTH ==="
systemctl is-active bluetooth && echo "bluetooth active" || echo "bluetooth not active"
echo ""
echo "=== WAYLAND SESSION ==="
echo "XDG_SESSION_TYPE: ${XDG_SESSION_TYPE:-unknown}"
